###
### A complete description of a Prefect Deployment for flow 'Koopa'
###
name: koopa-a-0.0.1
description: "Core koopa workflow.\n
  \n
  Arguments:\n
      * config_path: Path to koopa configuration file.\n
          Path must be passed linux-compatible (e.g. /tungstenfs/scratch/...).\n
          The default configuration file can be viewed and downloaded [here](https://github.com/BBQuercus/koopa/blob/main/koopa-prefect/koopa.cfg).\n
  \n
      * force: If selected, the entire workflow will be re-run.\n
          Otherwise, only the not yet executed components (missing files) are run.\n
  \n
  All documentation can be found on the koopa wiki (https://github.com/BBQuercus/koopa/wiki)."
version: 0.0.1
# The work queue that will handle this deployment's runs
work_queue_name: default
parameters: {}
schedule: null
infra_overrides: {}
infrastructure:
  type: process
  env: {}
  labels: {}
  name: null
  command: null
  stream_output: true
  working_dir: null
  block_type_slug: process
  _block_type_slug: process

###
### DO NOT EDIT BELOW THIS LINE
###
flow_name: Koopa
manifest_path: null
storage: null
path: /tungstenfs/scratch/gchao/eichbast/koopa/koopa-prefect/src
entrypoint: flows.py:workflow
parameter_openapi_schema:
  title: Parameters
  type: object
  properties:
    config_path:
      title: config_path
      type: string
    force:
      title: force
      default: false
      type: boolean
  required:
  - config_path
  definitions: null
